[serverConfig]

    ServerPort = "8000" #Required to input as string
    ServerAddr = "192.168.1.7" #Put in the IP address you want to bind to as string
    #Relative or absolute path accepted, the server will convert any relative path to an absolute path.

[documentLibrary]
    DocumentFileSystemLocation = 'documents' #Location to store documents
    DefaultNewDocumentFolder = 'New' #default folder that ingressed documents will be placed in (inside the Document library), for multiple folders deep can do '2020/New'

[ingress]
    IngressPath = 'ingress' #default path that the server will scan for new documents
    [ingress.scheduling]
        #number of minutes between scans of the ingress folder
        IngressInterval = 10
    [ingress.completed]
        #If True will delete files from ingress folder after processed (will leave ones if they produce error), if false will move to another folder
        IngressDeleteOnProcess = false 
        IngressMoveFolder = 'done' #default path that the server will move processed ingress documents to

[ocr]
    #Path to Tesseract binary (required for OCR)
    TesseractBin = "/usr/local/bin/tesseract"
    #Path to ImageMagick (required for OCR)
    MagickBin = "/usr/local/bin/magick"

[authentication]
    WebUIAuth = false # bool, if false no authentication is required for the webUI
    WebUIUser = "admin"
    WebUIPassword = "Password1"

[reverseProxy]
    #This is for setting up goTorrent behind a reverse Proxy (with SSL)
    ProxyEnabled = false #bool, either false or true
    #URL is CASE SENSITIVE
    BaseURL = "domain.com/subroute/"  # MUST be in the format (if you have a subdomain, and must have trailing slash) "yoursubdomain.domain.org/subroute/"

[frontend]
    NewDocumentNumber = 5 # number of new documents to fetch to view

[logging]

    Level = "debug" #debug, info, warn, error, fatal
    Encoding = "console" #JSON, console
    OutputPaths = ["stdout", "console"]
    ErrorOutPutPaths = ["stderr"]

[notifications]

    PushBulletToken = "" #add your pushbullet api token here to notify of torrent completion to pushbullet

